### ISSUE TITLE
About source and target files

### ISSUE THREAD

**Issue by carlitoselmago** [cyhuang-tw/AutoVC#2]
Hi, I was trying to use the inference.py script with the pretrained models you mention in README. I'm not sure if source and target are meant to be wav files? I'm trying this on windows10 with anaconda and get lots of errors like:

`TypeError: Invalid file: WindowsPath('source.wav')`

**Comment by cyhuang-tw** [comment]
Hi,

Sorry for the late reply.
The source and target are paths of WAV files. I'm not sure if the backslash used in Windows caused the problem. In this case, you can try to use raw string to solve it.
